name: Snake Commit SVG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_token: ${{ secrets.SECRETCODE }}
          github_user_name: Zallxupuu
          outputs: github-snake.svg   # gunakan 'outputs', bukan 'output'

      - name: Commit SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-snake.svg
          git commit -m "Update Snake SVG" || echo "No changes to commit"
          git push
